# Welcome to Jekyll!
# (I need to learn more about Ruby gem coding) 
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Angel (Zian) Chen 
email: angelc34@uw.edu 
description: > # this means to ignore newlines until "baseurl:"
  Many thanks to my web_master mentor Ben Erickson, who guided me setting up my first website. 
  Write an awesome description for your new site here. 
  
baseurl: "https://angelc34.pythonanywhere.com/" # the subpath of your site, e.g. /blog
url: "https://angelc34.github.io/" # the base hostname & protocol for your site
twitter_username: Zian_Chen
github_username: angelc34 


# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
